ALTER TABLE apps ADD COLUMN build_mode TEXT NOT NULL DEFAULT 'compose';
ALTER TABLE apps ADD COLUMN builder_image TEXT NOT NULL DEFAULT '';
ALTER TABLE apps ADD COLUMN build_command TEXT NOT NULL DEFAULT '';
ALTER TABLE apps ADD COLUMN run_command TEXT NOT NULL DEFAULT '';
ALTER TABLE apps ADD COLUMN listen_port INTEGER NOT NULL DEFAULT 0;
