ALTER TABLE apps ADD COLUMN kind TEXT NOT NULL DEFAULT 'web';
ALTER TABLE apps ADD COLUMN runtime TEXT NOT NULL DEFAULT '';
ALTER TABLE apps ADD COLUMN runtime_version TEXT NOT NULL DEFAULT '';
ALTER TABLE apps ADD COLUMN entrypoint TEXT NOT NULL DEFAULT '';
ALTER TABLE apps ADD COLUMN scale_to_zero INTEGER NOT NULL DEFAULT 0;
ALTER TABLE apps ADD COLUMN idle_timeout INTEGER NOT NULL DEFAULT 0;
ALTER TABLE apps ADD COLUMN last_invoked_at INTEGER NOT NULL DEFAULT 0;
