package composer

import (
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestResolveBinds(t *testing.T) {
	r := NewRuntime(nil, "/tmp/apps-root")
	sourceDir := "/tmp/apps-root/sources/app-uuid"

	spec := &Spec{Volumes: map[string]Volume{
		"dbdata": {},
	}}

	t.Run("named volume in spec passes through", func(t *testing.T) {
		out, err := r.resolveBinds([]string{"dbdata:/var/lib/db"}, sourceDir, spec)
		if err != nil || len(out) != 1 || out[0] != "dbdata:/var/lib/db" {
			t.Fatalf("out=%v err=%v", out, err)
		}
	})

	t.Run("undeclared named volume passes through", func(t *testing.T) {
		out, err := r.resolveBinds([]string{"cache:/cache"}, sourceDir, spec)
		if err != nil || len(out) != 1 || out[0] != "cache:/cache" {
			t.Fatalf("out=%v err=%v", out, err)
		}
	})

	t.Run("relative path resolves under source dir", func(t *testing.T) {
		out, err := r.resolveBinds([]string{"./data:/data"}, sourceDir, spec)
		if err != nil || len(out) != 1 {
			t.Fatalf("out=%v err=%v", out, err)
		}
		if out[0] != sourceDir+"/data:/data" {
			t.Fatalf("out[0]=%q", out[0])
		}
	})

	t.Run("absolute host path rejected", func(t *testing.T) {
		for _, m := range []string{"/etc:/etc", "/:/host", "/home/albertoruiz/.ssh:/keys:ro"} {
			if _, err := r.resolveBinds([]string{m}, sourceDir, spec); err == nil {
				t.Errorf("mount %q must be rejected", m)
			}
		}
	})

	t.Run("relative traversal rejected", func(t *testing.T) {
		for _, m := range []string{"../escape:/x", "./a/../../out:/x"} {
			if _, err := r.resolveBinds([]string{m}, sourceDir, spec); err == nil {
				t.Errorf("mount %q must be rejected", m)
			} else if !strings.Contains(err.Error(), "escapes") && !strings.Contains(err.Error(), "not allowed") {
				t.Errorf("mount %q: unexpected error %v", m, err)
			}
		}
	})
}

func TestWriteBuildContextEnv(t *testing.T) {
	dir := t.TempDir()
	r := &Runtime{} // Log nil → progress lines discarded
	path := filepath.Join(dir, ".env.local")

	// Writes a managed file with sorted KEY=VALUE lines.
	if err := r.writeBuildContextEnv(dir, map[string]string{"B": "2", "A": "1"}); err != nil {
		t.Fatal(err)
	}
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	want := "# generated by space-elevator (app env, build-time reads)\nA=1\nB=2\n"
	if string(b) != want {
		t.Errorf(".env.local = %q, want %q", b, want)
	}

	// A later deploy overwrites its own file (env changed on redeploy).
	if err := r.writeBuildContextEnv(dir, map[string]string{"A": "9"}); err != nil {
		t.Fatal(err)
	}
	b, _ = os.ReadFile(path)
	if !strings.Contains(string(b), "A=9") || strings.Contains(string(b), "B=2") {
		t.Errorf("managed .env.local not refreshed: %q", b)
	}

	// A repo-provided .env.local (no marker) is left untouched.
	if err := os.WriteFile(path, []byte("REPO_KEY=repo\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := r.writeBuildContextEnv(dir, map[string]string{"A": "9"}); err != nil {
		t.Fatal(err)
	}
	b, _ = os.ReadFile(path)
	if string(b) != "REPO_KEY=repo\n" {
		t.Errorf("repo-owned .env.local was modified: %q", b)
	}

	// Empty env writes nothing.
	dir2 := t.TempDir()
	if err := r.writeBuildContextEnv(dir2, nil); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir2, ".env.local")); !errors.Is(err, fs.ErrNotExist) {
		t.Error("empty env must not create .env.local")
	}
}
